# Generated by Django 3.0.7 on 2021-08-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun', models.CharField(max_length=255)),
                ('sana', models.DateField()),
                ('nomi', models.CharField(max_length=255)),
                ('malumot', models.TextField()),
                ('rasmi', models.ImageField(upload_to='news')),
                ('telegram', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
